### ISSUE TITLE
image send error

### ISSUE THREAD

**Issue by DeLuca92** [joaomirandasa/whats2api#27]
```bash
CMD CURL: curl --location --request POST 'localhost:8000/83430/sendFile?token=j19ksi1mim1lksm12213' \
--header 'Content-Type: application/json' \
--data-raw '{
	"phone":"5551979XXXXXX@c.us",
	"body": "https://upload.wikimedia.org/wikipedia/ru/3/33/NatureCover2001.jpg",
	"filename": "NatureCover2001.jpg",
	"caption": "W2API - Best REST API for WhatsApp"
}'
```

Output:
======= 2020-05-20 13:56:13: Error: Evaluation failed: t Error: Evaluation failed: t
    at ExecutionContext._evaluateInternal (/home/daniel/Desktop/whats2api-master/node_modules/puppeteer/lib/ExecutionContext.js:102:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/home/daniel/Desktop/whats2api-master/node_modules/puppeteer/lib/helper.js:94:19)
    at DOMWorld.evaluate (/home/daniel/Desktop/whats2api-master/node_modules/puppeteer/lib/DOMWorld.js:89:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/home/daniel/Desktop/whats2api-master/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.evaluate (/home/daniel/Desktop/whats2api-master/node_modules/puppeteer/lib/Page.js:591:14)
    at Page.<anonymous> (/home/daniel/Desktop/whats2api-master/node_modules/puppeteer/lib/helper.js:95:27)
    at Client.<anonymous> (/home/daniel/Desktop/whats2api-master/node_modules/@open-wa/wa-automate/dist/api/Client.js:430:50)
    at step (/home/daniel/Desktop/whats2api-master/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:23)
    at Object.next (/home/daniel/Desktop/whats2api-master/node_modules/@open-wa/wa-automate/dist/api/Client.js:25:53)
    at /home/daniel/Desktop/whats2api-master/node_modules/@open-wa/wa-automate/dist/api/Client.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/home/daniel/Desktop/whats2api-master/node_modules/@open-wa/wa-automate/dist/api/Client.js:15:12)
    at Client.sendImage (/home/daniel/Desktop/whats2api-master/node_modules/@open-wa/wa-automate/dist/api/Client.js:427:16)
  -- ASYNC --
    at Page.<anonymous> (/home/daniel/Desktop/whats2api-master/node_modules/puppeteer/lib/helper.js:94:19)
    at Client.<anonymous> (/home/daniel/Desktop/whats2api-master/node_modules/@open-wa/wa-automate/dist/api/Client.js:430:50)
    at step (/home/daniel/Desktop/whats2api-master/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:23)
    at Object.next (/home/daniel/Desktop/whats2api-master/node_modules/@open-wa/wa-automate/dist/api/Client.js:25:53)
    at /home/daniel/Desktop/whats2api-master/node_modules/@open-wa/wa-automate/dist/api/Client.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/home/daniel/Desktop/whats2api-master/node_modules/@open-wa/wa-automate/dist/api/Client.js:15:12)
    at Client.sendImage (/home/daniel/Desktop/whats2api-master/node_modules/@open-wa/wa-automate/dist/api/Client.js:427:16)
    at Client.<anonymous> (/home/daniel/Desktop/whats2api-master/node_modules/@open-wa/wa-automate/dist/api/Client.js:481:33)
    at step (/home/daniel/Desktop/whats2api-master/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:23)

I tried update npm, all repos and the same error :/

**Comment by joaomirandasa** [comment]
🤦🏽‍♂️ Attention, you're using PHONE parameter instead of CHATID, if you provide "@c.us" your parameter must be CHATID. 
Change that and let me know.

**Comment by DeLuca92** [comment]
OHh, sorry, bro :/.
I now works.
Sorry again
