### ISSUE TITLE
Puppeteer Protocol error (Runtime.callFunctionOn): Session closed [closed]

### ISSUE THREAD

**Issue by ismaelivan** [joaomirandasa/whats2api#58]
Two months ago I implemented this project and it had worked correctly (I send about 10 messages a day), but two days ago I can't connect, I already updated everything with npm update, also @ open-wa / wa-automate, @ open-wa / wa-decrypt, puppeteer and chromium. And it still doesn't work.

It shows me the qr-code, I scan it but the following appears:

V Authenticate to continue 
V Loading QR 
V WAPI Reinjected 
× The session is invalid. Retrying

`======= 2020-11-06 12:45:53: Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed. Error: Protocol error (Runtim e.callFunctionOn): Session closed. Most likely the page has been closed. at CDPSession.send (C:\Users\Ivan\Sources\wapi\node_modules\puppeteer\lib\Connection.js:141:35) at ExecutionContext._evaluateInternal (C:\Users\Ivan\Sources\wapi\node_modules\puppeteer\lib\ExecutionContext.js:85:50) at ExecutionContext.evaluate (C:\Users\Ivan\Sources\wapi\node_modules\puppeteer\lib\ExecutionContext.js:33:27) at ExecutionContext. (C:\Users\Ivan\Sources\wapi\node_modules\puppeteer\lib\helper.js:95:27) at DOMWorld.evaluate (C:\Users\Ivan\Sources\wapi\node_modules\puppeteer\lib\DOMWorld.js:89:24) -- ASYNC -- at Frame. (C:\Users\Ivan\Sources\wapi\node_modules\puppeteer\lib\helper.js:94:19) at Page.evaluate (C:\Users\Ivan\Sources\wapi\node_modules\puppeteer\lib\Page.js:612:14) at Page. (C:\Users\Ivan\Sources\wapi\node_modules\puppeteer\lib\helper.js:95:27) at checkIfCanAutoRefresh (C:\Users\Ivan\Sources\wapi\node_modules@open-wa\wa-automate\dist\controllers\auth.js:86:63) at Object. (C:\Users\Ivan\Sources\wapi\node_modules@open-wa\wa-automate\dist\controllers\auth.js:109:32) at step (C:\Users\Ivan\Sources\wapi\node_modules@open-wa\wa-automate\dist\controllers\auth.js:52:23) at Object.next (C:\Users\Ivan\Sources\wapi\node_modules@open-wa\wa-automate\dist\controllers\auth.js:33:53) at C:\Users\Ivan\Sources\wapi\node_modules@open-wa\wa-automate\dist\controllers\auth.js:27:71 at new Promise () at __awaiter (C:\Users\Ivan\Sources\wapi\node_modules@open-wa\wa-automate\dist\controllers\auth.js:23:12) -- ASYNC -- at Page. (C:\Users\Ivan\Sources\wapi\node_modules\puppeteer\lib\helper.js:94:19) at checkIfCanAutoRefresh (C:\Users\Ivan\Sources\wapi\node_modules@open-wa\wa-automate\dist\controllers\auth.js:86:63) at Object. (C:\Users\Ivan\Sources\wapi\node_modules@open-wa\wa-automate\dist\controllers\auth.js:109:32) at step (C:\Users\Ivan\Sources\wapi\node_modules@open-wa\wa-automate\dist\controllers\auth.js:52:23) at Object.next (C:\Users\Ivan\Sources\wapi\node_modules@open-wa\wa-automate\dist\controllers\auth.js:33:53) at C:\Users\Ivan\Sources\wapi\node_modules@open-wa\wa-automate\dist\controllers\auth.js:27:71 at new Promise () at __awaiter (C:\Users\Ivan\Sources\wapi\node_modules@open-wa\wa-automate\dist\controllers\auth.js:23:12) at Object.retrieveQR (C:\Users\Ivan\Sources\wapi\node_modules@open-wa\wa-automate\dist\controllers\auth.js:100:12) at C:\Users\Ivan\Sources\wapi\node_modules@open-wa\wa-automate\dist\controllers\initializer.js:216:55`

.... and it shows me the qr-code every 30 seconds

If I enter through the browser I have no problem, so there is no type of ban, I think it may be a block of the type 'non-secure page' by chromium, I also found this by puppeteer:

"It appears puppeteer has some dependency on the operating system it is deployed to. This causes some pages to silently crash 'Page has been closed.'"

[Update]: *** I already delete the myinstance.node.js file from the folder whatsSessionsr, and it won't rebuild it 

But I don't know how to correct it, could you help me? Thanks in advance!

**Comment by gautammd** [comment]
It had a similar issue but, it works when you update to the latest version of @open-wa\wa-automate. Just change to the latest version number on package.json and do "npm i"
