### ISSUE TITLE
QR CODE PROBLEM.

### ISSUE THREAD

**Issue by brumathey** [joaomirandasa/whats2api#65]
ReferenceError: WA_CLIENT is not defined<br> at Controller.view_qrcode (/app/htdocs/whats.eyou.com.br/whats2api/controllers/api.js:692:2)<br> at IncomingMessage.PROTO.$total_execute2 (/app/htdocs/whats.eyou.com.br/whats2api/node_modules/total.js/index.js:16934:32)<br> at IncomingMessage.PROTO.$total_execute (/app/htdocs/whats.eyou.com.br/whats2api/node_modules/total.js/index.js:16902:9)<br> at IncomingMessage.PROTO.$total_prepare (/app/htdocs/whats.eyou.com.br/whats2api/node_modules/total.js/index.js:17236:9)<br> at IncomingMessage.PROTO.$total_end (/app/htdocs/whats.eyou.com.br/whats2api/node_modules/total.js/index.js:16836:9)<br> at Framework.F.$requestcontinue (/app/htdocs/whats.eyou.com.br/whats2api/node_modules/total.js/index.js:8457:9)<br> at Server.F.listener (/app/htdocs/whats.eyou.com.br/whats2api/node_modules/total.js/index.js:8215:5)<br> at Server.emit (events.js:198:13)<br> at parserOnIncoming (_http_server.js:695:12)<br> at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)

**Comment by brumathey** [comment]
Any Sugestion?

**Comment by the-jojo-jj** [comment]
yes, i got same problem.

**Comment by mdestafadilah** [comment]
hallo any update here?
