### ISSUE TITLE
 Error: Evaluation failed: ReferenceError: getQrPng is not defined

### ISSUE THREAD

**Issue by the-jojo-jj** [joaomirandasa/whats2api#68]
suddenly, I got error: 

- Authenticate to continue

======= 2021-03-13 10:30:48: Error: Evaluation failed: ReferenceError: getQrPng is not defined

    at __puppeteer_evaluation_script__:1:1 Error: Evaluation failed: ReferenceError: getQrPng is not defined

    at __puppeteer_evaluation_script__:1:1

    at ExecutionContext._evaluateInternal (/var/www/w2api/node_modules/puppeteer/lib/ExecutionContext.js:56:23)

    at process._tickCallback (internal/process/next_tick.js:68:7)

  -- ASYNC --

    at ExecutionContext.<anonymous> (/var/www/w2api/node_modules/puppeteer/lib/helper.js:94:19)

    at DOMWorld.evaluate (/var/www/w2api/node_modules/puppeteer/lib/DOMWorld.js:89:24)

    at process._tickCallback (internal/process/next_tick.js:68:7)

  -- ASYNC --

    at Frame.<anonymous> (/var/www/w2api/node_modules/puppeteer/lib/helper.js:94:19)

    at Page.evaluate (/var/www/w2api/node_modules/puppeteer/lib/Page.js:612:14)

    at Page.<anonymous> (/var/www/w2api/node_modules/puppeteer/lib/helper.js:95:27)

    at Object.<anonymous> (/var/www/w2api/node_modules/@open-wa/wa-automate/dist/controllers/auth.js:132:59)

    at step (/var/www/w2api/node_modules/@open-wa/wa-automate/dist/controllers/auth.js:52:23)

    at Object.next (/var/www/w2api/node_modules/@open-wa/wa-automate/dist/controllers/auth.js:33:53)

    at /var/www/w2api/node_modules/@open-wa/wa-automate/dist/controllers/auth.js:27:71

    at new Promise (<anonymous>)

    at __awaiter (/var/www/w2api/node_modules/@open-wa/wa-automate/dist/controllers/auth.js:23:12)

    at grabAndEmit (/var/www/w2api/node_modules/@open-wa/wa-automate/dist/controllers/auth.js:128:62)

  -- ASYNC --

    at Page.<anonymous> (/var/www/w2api/node_modules/puppeteer/lib/helper.js:94:19)

    at Object.<anonymous> (/var/www/w2api/node_modules/@open-wa/wa-automate/dist/controllers/auth.js:132:59)

    at step (/var/www/w2api/node_modules/@open-wa/wa-automate/dist/controllers/auth.js:52:23)

    at Object.next (/var/www/w2api/node_modules/@open-wa/wa-automate/dist/controllers/auth.js:33:53)

    at /var/www/w2api/node_modules/@open-wa/wa-automate/dist/controllers/auth.js:27:71

    at new Promise (<anonymous>)

    at __awaiter (/var/www/w2api/node_modules/@open-wa/wa-automate/dist/controllers/auth.js:23:12)

    at grabAndEmit (/var/www/w2api/node_modules/@open-wa/wa-automate/dist/controllers/auth.js:128:62)

    at Object.<anonymous> (/var/www/w2api/node_modules/@open-wa/wa-automate/dist/controllers/auth.js:177:52)

    at step (/var/www/w2api/node_modules/@open-wa/wa-automate/dist/controllers/auth.js:52:23)

- QR scan took too long. Session Timed Out. Shutting down. Consider increasing qrTimeout config variable: https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#qrtimeout

======= 2021-03-13 10:31:48: Error: QR Timeout Error: QR Timeout

sombody else got the same?

**Comment by nanobyte84** [comment]
same problem here...

**Comment by smashah** [comment]
@nanobyte84 @the-jojo-jj you need to update the @open-wa/wa-automate dependency to the latest version.

Or just use the ready made CLI https://docs.openwa.dev/pages/Getting%20Started/quick-run.html

**Comment by the-jojo-jj** [comment]
@smashah thanks for your reply.
can you show me how to update the @open-wa/wa-automate dependency to the latest version?

**Comment by smashah** [comment]
Try this 

https://www.npmjs.com/package/npm-force-resolutions
