### ISSUE TITLE
Unable to get QR code

### ISSUE THREAD

**Issue by manojsitapara** [joaomirandasa/whats2api#76]
I am getting following error, can someone please help me to fix this error?

`======= 2021-05-12 10:28:08: TypeError: Cannot create property 'eventMode' on string '/whatsSessions/83430' TypeError: Cannot create property 'eventMode' on string '/whatsSessions/83430'
    at Object.<anonymous> (/var/www/w2api/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:81:30)
    at Generator.next (<anonymous>)
    at /var/www/w2api/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/var/www/w2api/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:23:12)
    at Object.create (/var/www/w2api/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:74:12)
    at Framework.<anonymous> (/var/www/w2api/modules/whatsapp.js:216:10)
    at global.EMIT.F.emit (/var/www/w2api/node_modules/total.js/index.js:1526:11)
    at Timeout._onTimeout (/var/www/w2api/node_modules/total.js/index.js:7722:7)
    at listOnTimeout (node:internal/timers:557:17)`

![image](https://user-images.githubusercontent.com/12126671/117961260-8b831c80-b33b-11eb-956a-c57009a7fd9e.png)

here is my package.json

`{
  "name": "w2api-master",
  "version": "0.0.9",
  "description": "An Javascript based WhatsApp library for connect your data as API",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/joaomirandasa/whats2api.git"
  },
  "keywords": [
    "whatsapp",
    "api",
    "whatsapp",
    "api",
    "puppeter"
  ],
  "author": "João Vitor Miranda Santos",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/joaomirandasa/whats2api/issues"
  },
  "homepage": "https://github.com/joaomirandasa/whats2api#readme",
  "dependencies": {
    "@open-wa/wa-automate": "^3.11.3",
    "async": "^3.2.0",
    "download-file": "^0.1.5",
    "minimist": ">=1.2.5",
    "moment": "^2.29.1",
    "puppeteer": "^9.1.1",
    "request": "^2.88.2",
    "total.js": "^3.4.8",
    "vcards-js": "^2.10.0"
  }
}
`

**Comment by julianokunha** [comment]
Tenho o mesmo problema, inclusive fui tentar usar mais tive tantos erros de dependências ultrapassadas que desisti.

**Comment by manojsitapara** [comment]
@julianokunha thank you for comment and feedback, did you find out any alternative solution.

Right now I am using docker container for each new WhatsApp instance, but looks like it's not feasible solution.

Please suggest if you have better idea or suggestions.

Thank you.
